Added event logging in database
justbetter/laravel-magento-webhooks pull request #8
Opened 2024-01-25 11:43 UTC by fritsjustbetter

2024-01-25 11:58 UTC, VincentBean requested changes

2024-01-25 11:58 UTC, VincentBean commented on database/migrations/2024_01_24_153000_create_event_log_table.php
> +        Schema::create('event_logs', function (Blueprint $table): void {
Please prefix `magento_webhooks`

2024-01-30 12:11 UTC, ramonrietdijk requested changes

2024-01-30 12:11 UTC, ramonrietdijk commented on README.md
> +This command supports usage of a custom date, this date will indicate removing the logs from before that date, this defaults to one month.
Please, rewrite this sentence. Also, the `--force` option does not exist.

2024-01-30 12:11 UTC, ramonrietdijk commented on UPGRADE.md
> +# 1.x to 2.x
The type of headings are incorrect. Use `#`, `##` and `###`

2024-01-30 12:11 UTC, ramonrietdijk commented on src/Models/EventLog.php
> + * @property Carbon $created_at
Both `created_at` and `updated_at` are nullable

2024-01-30 12:11 UTC, ramonrietdijk commented on tests/Actions/CleanLogsTest.php
> +namespace Actions;
Namespace is incorrect

2024-01-30 12:11 UTC, ramonrietdijk commented on tests/Commands/CommandDispatchTest.php
Not a great name for a test, please rename to `CleanLogsCommandTest`

2024-01-30 12:11 UTC, ramonrietdijk commented on tests/Commands/CommandDispatchTest.php
> +    public function test_it_dispatches_job(): void
It's helpful to have more descriptive test cases as it currently doesn't tell that much. Also, the `test_` prefix is not required with the `@test` comment.

2024-01-30 12:11 UTC, ramonrietdijk commented on tests/Jobs/CleanLogsJobTest.php
> +namespace Jobs;
Namespace is incorrect

2024-01-30 12:11 UTC, ramonrietdijk commented on tests/Jobs/CleanLogsJobTest.php
> +    public function it_can_dispatch_events(): void
Test case does not seem correct

2024-02-01 12:13 UTC, ramonrietdijk approved these changes

2024-02-01 12:18 UTC, VincentBean commented
Please fix the failing tests :)

2024-02-01 12:18 UTC, VincentBean approved these changes

2024-02-01 12:21 UTC, merged